version: "3.5"

services:
  jwt_redis:
    container_name: jwt_redis
    image: redis:5.0
    networks:
      - jwt-work
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./db/redis/jwt_data:/data

  jwt_phpmyadmin:
    container_name: jwt_phpmyadmin
    image: phpmyadmin/phpmyadmin
    networks:
      - jwt-work
    environment:
      - PMA_HOST=jwt_mysql
    links:
      - "jwt_mysql:jwt_mysql"
    ports:
      - 8090:80

  jwt_mysql:
    container_name: jwt_mysql
    image: mysql:5.6
    networks:
      - jwt-work
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Taipei
    ports:
      - 3316:3306
    volumes:
      - ./db/mysql/data:/var/lib/mysql

networks:
  jwt-work:
    name: jwt-work
    driver: bridge
